# Generated by Django 4.2.7 on 2024-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_pdf_file_security_pdf_continue_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='security_pdf',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
